<!doctype html>
<html>
<head>
<title>Librarian</title>
</head>
<body>
<h1>Book</h1>
<form method="post" action="index.php?c=book&a=save">
<label for="title">Title:</label>
<input type="text" name="title" value="<?=$this->book->title?>"><br/>
<label for="author_code">Author:</label>
<select name="author_code">
<?=$this->listAuthorsForSelect($this->book->author->code ?? 0)?>
</select><br/>
<input type="hidden" name="code" value="<?=$this->book->code?>"><br/>
<input type="submit" value="save">
</form>    
</body>    
</html>
