rm authors.txt
rm authors.test.txt
rm books.txt
rm books.test.txt
rm authors.csv
rm authors.test.csv
rm books.csv
rm books.test.csv
rm authors.json
rm authors.test.json
rm books.json
rm books.test.json
rm *.bkp
